### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [EarlOfEgo/stopmotion#30]
Do you still maintain this app, @EarlOfEgo – or have you stopped it? There was no commit for almost 2 years, so I wonder…

**Comment by EarlOfEgo** [comment]
Hi, no I don't actively maintain it anymore. But if you want to submit a pull request I will review it and most likely merge it.

**Comment by IzzySoft** [comment]
@EarlOfEgo thanks for your answer! I'm not a dev, so sorry I cannot contribute a PR. My only contribution is to offer your app [via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.sthagios.stopmotion) so it can be found with the F-Droid client …

**Comment by EarlOfEgo** [comment]
Oh nice, thank you.
